### PR TITLE
[Core] Fix grouped type properties not swapping properly

### LINKED ISSUE #525: Crash adding item to collection with no properties
1. Add a suggested type that has properties
2. Add an instance of the type from 1.
3. Add a suggested type that has no properties
4. Add an instance of the type from 3.
Boom.

### PR DESCRIPTION
**Pull request by ermau**
Fixes #525

When we moved to the new panel group system, the grouped editors weren't
accounted for and so when we try to remove their child property from the
container group it's not found since they're inside the group editor VM.

This also meant that even if removal had worked, we wouldn't properly
add new shared view model types to the group.

This version addresses the crasher listed in #527, the second issue was a false alarm.

### CODE REVIEW

File: Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs [hunk 1]
```diff
@@ -246,19 +271,20 @@ protected override void OnAddEditors (IEnumerable<EditorViewModel> editors)
...
-				if (remainingItems != null) // TODO: pretty sure this was out of order before, add test
-					this.arranged.Add (key, new PanelGroupViewModel (key, grouping.Where (evm => remainingItems.Contains (evm))));
-				else
-					this.arranged.Add (key, new PanelGroupViewModel (key, grouping, separateUncommon: !isFlat));
+				string key = grouping.Key;
+				if (remainingItems != null) {// TODO: pretty sure this was out of order before, add test
+					if (remainingItems.Count > 0)
+						this.arranged.Add (key, new PanelGroupViewModel (TargetPlatform, key, grouping.Where (evm => remainingItems.Contains (evm))));
+				} else
+					this.arranged.Add (key, new PanelGroupViewModel (TargetPlatform, key, grouping, separateUncommon: !isFlat));
```
Comment (bleroy) [inline Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs]: Not from this change, but it's unclear why we care about `separateUncommon` in one case and not the other. Might want to add a comment when you get the chance.

File: Xamarin.PropertyEditing/ViewModels/PropertyGroupViewModel.cs [hunk 2]
```diff
@@ -55,10 +55,35 @@ public string FilterText
 			}
 		}
 
-		private readonly PropertyViewModel[] properties;
+		public void Add (PropertyViewModel property)
+		{
+			if (property == null)
+				throw new ArgumentNullException (nameof(property));
+
+			this.properties.Add (property);
```
Comment (bleroy) [inline Xamarin.PropertyEditing/ViewModels/PropertyGroupViewModel.cs]: So why is it not added to `propertiesView`?

Comment (ermau) [reply Xamarin.PropertyEditing/ViewModels/PropertyGroupViewModel.cs]: `Reload()` handles that.

File: Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs (hunk 1 above)
Comment (ermau) [reply Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs]: In the first case we can assume we're in a grouped mode as there wouldn't be remaining items otherwise. We could pass the same `!isFlat` to make things clearer I suppose, it would always be `true`.
